### ISSUE TITLE
Add support for Teradata as a JDBC persistence

### ISSUE THREAD

**Issue by konjason** [nhachem/stitchr#17]

**Comment by nhachem** [comment]
We need to add the maven dependency in thee pom.xml file and rebuild the jar. 
Then any data_persistence entry that specifies a jdbc teradata source will be active

**Comment by nhachem** [comment]
For Teradata (and also oracle) the jdbc drivers are not readily available on maven.... We added code to register the jars in the local maven repo so that th build would pick them up.
